version: '3'

services:
  cdc-streamer:
    build:
      context: ./cdc
      dockerfile: Dockerfile.streamer
    env_file:
      - ./cdc/.env
    volumes:
      - ./cdc/logs:/app/logs
      - ./cdc/output:/app/output
      - ./cdc/sa.json:/app/sa.json
    network_mode: host

  cdc-uploader:
    build:
      context: ./cdc
      dockerfile: Dockerfile.uploader
    env_file:
      - ./cdc/.env
    volumes:
      - ./cdc/logs:/app/logs
      - ./cdc/output:/app/output
      - ./cdc/sa.json:/app/sa.json

  cdc-producer:
    build:
      context: ./cdc
      dockerfile: Dockerfile.producer
    env_file:
      - ./cdc/.env
    network_mode: host
