- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install required system packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "python{{ python_version }}"
    - "python{{ python_version }}-venv"

- name: Clone this repository
  git:
    repo: git@github.com-demo:rdxz2/demo.git
    dest: "{{ repo_dir }}"
    version: "{{ git_branch }}"

- name: Ensure venv directory exists
  file:
    path: "{{ venv_dir }}"
    state: directory

- name: Ensure service account directory exists
  file:
    path: "{{ sa_dir }}"
    state: directory
