# Installation

- name: Ensure Metabase home directory exists
  file:
    path: "{{ metabase_home_dir }}"
    state: directory

- name: Download Metabase
  get_url:
    url: https://downloads.metabase.com/{{ metabase_version }}/metabase.jar
    dest: "{{ metabase_home_dir }}/metabase-{{ metabase_version }}"
    mode: 0600
