all:
  # Global variables in environment level
  vars:
    docker_repository_host: asia-southeast2-docker.pkg.dev
    docker_repository_project_id: ageless-aura-462704-t4
    docker_repository_name: demo

    gcp_project_id: ageless-aura-462704-t4
    gcp_region: asia-southeast2
    gcp_zone: asia-southeast2-b

    # gcs_bucket: xz2-demo

    # bq_project_id: xz2-demo
    # bq_dataset_location: asia-southeast2
    # bq_dataset_id_datalake: datalake

    # cdc_bq_log_dataset_prefix: cdclog__

  hosts:
    producers:
      ansible_host: 10.0.0.100
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: -o ProxyCommand="gcloud compute start-iap-tunnel %h %p --listen-on-stdin --project={{ gcp_project_id }} --zone={{ gcp_zone }}"

      dummydb_host: 10.0.0.100
      dummydb_port: 5432
      dummydb_name: dummydb
      dummydb_user: dummy
      dummydb_pass: "{{ secret__dummydb_pass }}"

    # airflows:
    #   ansible_host: 10.0.0.5
    #   ansible_user: ubuntu

    #   airflow_version: 2.10.4
    #   airflow_webserver_url: https://airflow.rdxz2.site
    #   airflow_home_dir: "{{ home_dir }}/airflow"
    #   airflow_venv_dir: "{{ venv_dir }}/airflow"
    #   airflow_repo_dir: "{{ repo_dir }}/airflow"

    #   db_airflow_host: 10.0.0.5
    #   db_airflow_port: 5432
    #   db_airflow_user: airflow
    #   db_airflow_name: airflow

    #   db_cdc_host: 10.0.0.5
    #   db_cdc_port: 5432
    #   db_cdc_user: airflow
    #   db_cdc_name: cdc

    #   db_metabase_host: 10.0.0.5
    #   db_metabase_port: 5432
    #   db_metabase_user: airflow
    #   db_metabase_name: metabase

    #   cdc_merger_target_conn_ids: # List of streamed databases to be merged
    #     - pg_metabase

    # cdcs:
    #   ansible_host: 10.0.0.5
    #   ansible_user: ubuntu

    #   cdc_home_dir: "{{ home_dir }}/cdc"
    #   cdc_venv_dir: "{{ venv_dir }}/cdc"
    #   cdc_repo_dir: "{{ repo_dir }}/cdc"

    #   cdc_targets:
    #     metabase:
    #       cdc_db_host: 10.0.0.5
    #       cdc_db_port: 5432
    #       cdc_db_user: repl
    #       cdc_db_name: metabase
    #       cdc_publ_name: metabase
    #       cdc_slot_name: metabase

    # metabases:
    #   ansible_host: 10.0.0.5
    #   ansible_user: ubuntu

    #   metabase_version: v0.52.2
    #   metabase_home_dir: "{{ home_dir }}/metabase"

    #   # Env vars
    #   mb_db_type: postgres
    #   mb_db_host: 10.0.0.5
    #   mb_db_port: 5432
    #   mb_db_user: metabase
    #   mb_db_dbname: metabase
    #   mb_admin_email: richard.dharmawan@gmail.com
    #   mb_anon_tracking_enabled: false
    #   mb_db_query_timeout_minutes: 1
    #   mb_download_row_limit: -1 # Disable downloads e.g. the file will contains error stack without showing sensitive data
    #   mb_google_auth_enabled: true
    #   mb_site_name: XZ2 Demo
    #   mb_site_url: https://metabase.rdxz2.site
    #   mb_enable_xrays: false
    #   mb_show_homepage_xrays: false
    #   mb_show_homepage_data: false
    #   mb_report_timezone: "{{ timezone }}"
    #   mb_humanization_strategy: none # Just show the database original object names
    #   mb_native_query_autocomplete_match_style: prefix # Increase performance in large database
    #   mb_enable_test_endpoints: false
    #   mb_load_sample_content: false
    #   mb_password_complexity:
    #   mb_password_length:
    #   mb_start_of_week: monday
    #   mb_enable_public_sharing: false
    #   mb_enable_query_caching: false
    #   mb_query_caching_max_ttl: 3600
    #   mb_query_caching_max_kb: 100
    #   mb_jetty_host: 0.0.0.0
    #   mb_jetty_port: 3000
