all:
  # Global variables in environment level
  vars:
    timezone: Asia/Jakarta

    gcp_project_id: xz2-demo
    gcp_region: asia-southeast2

    gcs_bucket: xz2-demo

    bq_project_id: xz2-demo
    bq_dataset_location: asia-southeast2
    bq_dataset_id_datalake: datalake

    cdc_bq_log_dataset_prefix: cdclog__

  hosts:
    airflows:
      ansible_host: 10.0.0.5
      ansible_user: ubuntu

      airflow_version: 2.10.4
      airflow_webserver_url: https://airflow.rdxz2.site
      airflow_home_dir: "{{ home_dir }}/airflow"
      airflow_venv_dir: "{{ venv_dir }}/airflow"
      airflow_repo_dir: "{{ repo_dir }}/airflow"

      db_airflow_host: 10.0.0.5
      db_airflow_port: 5432
      db_airflow_user: airflow
      db_airflow_name: airflow

      db_cdc_host: 10.0.0.5
      db_cdc_port: 5432
      db_cdc_user: airflow
      db_cdc_name: cdc

      db_metabase_host: 10.0.0.5
      db_metabase_port: 5432
      db_metabase_user: airflow
      db_metabase_name: metabase

      cdc_merger_target_conn_ids: # List of streamed databases to be merged
        - pg_metabase

    cdcs:
      ansible_host: 10.0.0.5
      ansible_user: ubuntu

      cdc_home_dir: "{{ home_dir }}/cdc"
      cdc_venv_dir: "{{ venv_dir }}/cdc"
      cdc_repo_dir: "{{ repo_dir }}/cdc"

      cdc_targets:
        metabase:
          cdc_db_host: 10.0.0.5
          cdc_db_port: 5432
          cdc_db_user: repl
          cdc_db_name: metabase
          cdc_publ_name: metabase
          cdc_slot_name: metabase
