# Env files

- name: Copy service environment variable file
  template:
    src: .env.metabase.j2
    dest: "{{ metabase_home_dir }}/.env.metabase"
    mode: 0700

# Configuration files

- name: Copy Metabase log configuration file
  template:
    src: log4j2.xml.j2
    dest: "{{ metabase_home_dir }}/log4j2.xml"
    mode: 0600

- name: Copy Metabase service file into systemd
  become: true
  template:
    src: metabase.service.j2
    dest: /etc/systemd/system/metabase.service
  register: copy_service_file_result

- name: Copy Metabase run script
  template:
    src: run.sh.j2
    dest: "{{ metabase_home_dir }}/run.sh"
    mode: 0700

# Services

- name: Reload systemd daemon
  become: true
  command: systemctl daemon-reload
  when: copy_service_file_result.changed

- name: Start Metabase service
  become: true
  systemd:
    name: metabase.service
    state: restarted
    enabled: yes
