# Installation

- name: Ensure Airflow home directory exists
  file:
    path: "{{ airflow_home_dir }}"
    state: directory

- name: Create virtual environment
  command:
    cmd: "python3.12 -m venv {{ airflow_venv_dir }}"
  args:
    creates: "{{ airflow_venv_dir }}/bin/activate"

- name: Install Airflow
  pip:
    executable: "{{ airflow_venv_dir }}/bin/pip"
    name:
      - apache-airflow=={{ airflow_version }}
    state: present
    extra_args: "--upgrade --constraint https://raw.githubusercontent.com/apache/airflow/constraints-{{ airflow_version }}/constraints-{{ python_version }}.txt"

- name: Install remaining pip packages
  pip:
    executable: "{{ airflow_venv_dir }}/bin/pip"
    requirements: "{{ airflow_repo_dir }}/requirements.txt"

# Configuration files

- name: Link webserver configuration file into Airflow home directory
  file:
    src: "{{ airflow_repo_dir }}/webserver_config.py"
    dest: "{{ airflow_home_dir }}/webserver_config.py"
    state: link

- name: Link webserver file into systemd
  become: true
  file:
    src: "{{ airflow_repo_dir }}/airflow-webserver.service"
    dest: /etc/systemd/system/airflow-webserver.service
    state: link

- name: Link scheduler file into systemd
  become: true
  file:
    src: "{{ airflow_repo_dir }}/airflow-scheduler.service"
    dest: /etc/systemd/system/airflow-scheduler.service
    state: link

# Env files

- name: Copy Airflow environment variable file
  template:
    src: .env.airflow.j2
    dest: "{{ airflow_home_dir }}/.env.airflow"
    mode: 0644

- name: Copy application dotenv file
  template:
    src: .env.j2
    dest: "{{ airflow_home_dir }}/.env"

- name: Fetch service account file
  google.cloud.gcp_secret_manager_secret:
    name: "{{ airflow_gcp_secret }}"
    project: "{{ gcp_project_id }}"
    version: latest
    state: present
  register: sa_airflow

- name: Copy service account file
  copy:
    content: "{{ sa_airflow.payload.data | b64decode }}"
    dest: "{{ sa_airflow_filename }}"

# Services

- name: Migrate database
  command:
    cmd: "source {{ airflow_home_dir }}/.env.airflow && {{ airflow_venv_dir }}/bin/airflow db migrate"

- name: Start the webserver
  systemd:
    name: airflow-webserver.service
    state: started
    enabled: yes

- name: Start the scheduler
  systemd:
    name: airflow-scheduler.service
    state: started
    enabled: yes
