# Installation

- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: true

- name: Ensure Docker service is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add current user to docker group
  ansible.builtin.group:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Authenticate Docker with Artifact Registry
  ansible.builtin.shell: |
    gcloud auth configure-docker {{ docker_repository_host }} --quiet
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ gcp_project_id }}"
