- name: Producer - Basic setup
  hosts: producers
  vars_files:
    - vars/main.yaml
  roles:
    - docker
  tags:
    - producer_basic

- name: Producer
  hosts: producers
  vars_files:
    - vars/main.yaml
    - "{{ secrets_file }}"
  roles:
    - producer
  tags:
    - producer
