- name: Producer - Basic
  hosts: producers
  vars_files:
    - vars/main.yaml
  roles:
    - docker
  tags:
    - basic

- name: Producer
  hosts: producers
  vars_files:
    - vars/main.yaml
    - "{{ secret_file }}"  # Must be absolute / path relative to this file
  roles:
    - producer
  tags:
    - producer
