- name: Basic setup - Airflow
  hosts: airflows
  vars_files:
    - vars/main.yaml
  roles:
    - setup
  tags:
    - airflow_setup

- name: Installation - Airflow
  hosts: airflows
  vars_files:
    - vars/main.yaml
  roles:
    - airflow
  tags:
    - airflow_install
