name: Build and push docker image

on:
  push:
    branches:
      - "*"
    # tags:
    #   - "*" # Triggers only on version tags like 0.0.1
    paths:
      - producer/**

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    steps:
      # Configuration

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker login to Artifact Registry
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin ${{ vars.AR_REPOSITORY }}

      - name: Checkout repository code
        uses: actions/checkout@v4

      # Execution

      - name: Build docker image
        run: |
          cd producer
          docker build . --tag ${{ vars.AR_REPOSITORY }}/producer

      - name: Push docker image
        run: |
          docker push ${{ vars.AR_REPOSITORY }}/producer

  ansible-deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-container
    steps:
      # Configuration

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install Ansible
        run: |
          sudo apt update && sudo apt install -y ansible

      - name: Install required Ansible Galaxy collections
        run: |
          ansible-galaxy collection install -r ansible/requirements.yaml

      - name: Setup SSH credentials for IAP tunneling
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_SECRET_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          echo -e "Host *\n  StrictHostKeyChecking no" > ~/.ssh/config

      - name: Checkout repository code
        uses: actions/checkout@v4

      # Execution

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/prod.yaml ansible/play-producer.yaml
